version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: photomanager
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  client:
    image: swift:5.3
    volumes:
      - .:/app
    working_dir: /app
    command: swift run Client
